// Type definitions for es-intrinsic-cache
// Project: https://github.com/xsfj/es-intrinsic-cache

/**
 * Available intrinsic names that can be retrieved.
 * This includes all JavaScript built-in intrinsics, their prototypes,
 * methods, and legacy aliases for compatibility.
 */
type IntrinsicName =
  | "%AggregateError%"
  | "%Array%"
  | "%Array.prototype%"
  | "%Array.prototype.concat%"
  | "%Array.prototype.entries%"
  | "%Array.prototype.every%"
  | "%Array.prototype.filter%"
  | "%Array.prototype.find%"
  | "%Array.prototype.findIndex%"
  | "%Array.prototype.forEach%"
  | "%Array.prototype.includes%"
  | "%Array.prototype.indexOf%"
  | "%Array.prototype.join%"
  | "%Array.prototype.keys%"
  | "%Array.prototype.lastIndexOf%"
  | "%Array.prototype.map%"
  | "%Array.prototype.pop%"
  | "%Array.prototype.push%"
  | "%Array.prototype.reduce%"
  | "%Array.prototype.reduceRight%"
  | "%Array.prototype.reverse%"
  | "%Array.prototype.shift%"
  | "%Array.prototype.slice%"
  | "%Array.prototype.some%"
  | "%Array.prototype.sort%"
  | "%Array.prototype.splice%"
  | "%Array.prototype.unshift%"
  | "%Array.prototype.values%"
  | "%ArrayBuffer%"
  | "%ArrayBufferPrototype%"
  | "%ArrayIteratorPrototype%"
  | "%ArrayProto_entries%"
  | "%ArrayProto_forEach%"
  | "%ArrayProto_keys%"
  | "%ArrayProto_values%"
  | "%ArrayPrototype%"
  | "%AsyncFromSyncIteratorPrototype%"
  | "%AsyncFunction%"
  | "%AsyncFunctionPrototype%"
  | "%AsyncGenerator%"
  | "%AsyncGeneratorFunction%"
  | "%AsyncGeneratorPrototype%"
  | "%AsyncIteratorPrototype%"
  | "%Atomics%"
  | "%BigInt%"
  | "%BigInt64Array%"
  | "%BigUint64Array%"
  | "%Boolean%"
  | "%Boolean.prototype%"
  | "%BooleanPrototype%"
  | "%DataView%"
  | "%DataViewPrototype%"
  | "%Date%"
  | "%Date.prototype%"
  | "%DatePrototype%"
  | "%Error%"
  | "%Error.prototype%"
  | "%ErrorPrototype%"
  | "%EvalError%"
  | "%EvalErrorPrototype%"
  | "%FinalizationRegistry%"
  | "%Float16Array%"
  | "%Float32Array%"
  | "%Float32ArrayPrototype%"
  | "%Float64Array%"
  | "%Float64ArrayPrototype%"
  | "%Function%"
  | "%Function.prototype%"
  | "%Function.prototype.apply%"
  | "%Function.prototype.bind%"
  | "%Function.prototype.call%"
  | "%FunctionPrototype%"
  | "%Generator%"
  | "%GeneratorFunction%"
  | "%GeneratorPrototype%"
  | "%Int16Array%"
  | "%Int16ArrayPrototype%"
  | "%Int32Array%"
  | "%Int32ArrayPrototype%"
  | "%Int8Array%"
  | "%Int8ArrayPrototype%"
  | "%IteratorPrototype%"
  | "%JSON%"
  | "%JSON.parse%"
  | "%JSON.stringify%"
  | "%JSONParse%"
  | "%JSONStringify%"
  | "%Map%"
  | "%Map.prototype%"
  | "%MapIteratorPrototype%"
  | "%MapPrototype%"
  | "%Math%"
  | "%Math.abs%"
  | "%Math.acos%"
  | "%Math.asin%"
  | "%Math.atan%"
  | "%Math.atan2%"
  | "%Math.ceil%"
  | "%Math.cos%"
  | "%Math.exp%"
  | "%Math.floor%"
  | "%Math.log%"
  | "%Math.max%"
  | "%Math.min%"
  | "%Math.pow%"
  | "%Math.random%"
  | "%Math.round%"
  | "%Math.sign%"
  | "%Math.sin%"
  | "%Math.sqrt%"
  | "%Math.tan%"
  | "%Math.trunc%"
  | "%Number%"
  | "%Number.prototype%"
  | "%NumberPrototype%"
  | "%ObjProto_toString%"
  | "%ObjProto_valueOf%"
  | "%Object%"
  | "%Object.assign%"
  | "%Object.create%"
  | "%Object.defineProperties%"
  | "%Object.defineProperty%"
  | "%Object.entries%"
  | "%Object.freeze%"
  | "%Object.getOwnPropertyDescriptor%"
  | "%Object.getOwnPropertyDescriptors%"
  | "%Object.getOwnPropertyNames%"
  | "%Object.getOwnPropertySymbols%"
  | "%Object.getPrototypeOf%"
  | "%Object.is%"
  | "%Object.isExtensible%"
  | "%Object.isFrozen%"
  | "%Object.isSealed%"
  | "%Object.keys%"
  | "%Object.preventExtensions%"
  | "%Object.prototype%"
  | "%Object.prototype.hasOwnProperty%"
  | "%Object.prototype.isPrototypeOf%"
  | "%Object.prototype.propertyIsEnumerable%"
  | "%Object.prototype.toString%"
  | "%Object.prototype.valueOf%"
  | "%Object.seal%"
  | "%Object.setPrototypeOf%"
  | "%Object.values%"
  | "%ObjectPrototype%"
  | "%Promise%"
  | "%Promise.all%"
  | "%Promise.allSettled%"
  | "%Promise.any%"
  | "%Promise.prototype%"
  | "%Promise.prototype.catch%"
  | "%Promise.prototype.finally%"
  | "%Promise.prototype.then%"
  | "%Promise.race%"
  | "%Promise.reject%"
  | "%Promise.resolve%"
  | "%PromiseProto_then%"
  | "%PromisePrototype%"
  | "%Promise_all%"
  | "%Promise_reject%"
  | "%Promise_resolve%"
  | "%Proxy%"
  | "%RangeError%"
  | "%RangeErrorPrototype%"
  | "%ReferenceError%"
  | "%ReferenceErrorPrototype%"
  | "%Reflect%"
  | "%Reflect.getPrototypeOf%"
  | "%RegExp%"
  | "%RegExp.prototype%"
  | "%RegExpPrototype%"
  | "%Set%"
  | "%Set.prototype%"
  | "%SetIteratorPrototype%"
  | "%SetPrototype%"
  | "%SharedArrayBuffer%"
  | "%SharedArrayBufferPrototype%"
  | "%String%"
  | "%String.prototype%"
  | "%String.prototype.charAt%"
  | "%String.prototype.charCodeAt%"
  | "%String.prototype.concat%"
  | "%String.prototype.endsWith%"
  | "%String.prototype.includes%"
  | "%String.prototype.indexOf%"
  | "%String.prototype.lastIndexOf%"
  | "%String.prototype.match%"
  | "%String.prototype.padEnd%"
  | "%String.prototype.padStart%"
  | "%String.prototype.repeat%"
  | "%String.prototype.replace%"
  | "%String.prototype.search%"
  | "%String.prototype.slice%"
  | "%String.prototype.split%"
  | "%String.prototype.startsWith%"
  | "%String.prototype.substring%"
  | "%String.prototype.toLowerCase%"
  | "%String.prototype.toUpperCase%"
  | "%String.prototype.trim%"
  | "%StringIteratorPrototype%"
  | "%StringPrototype%"
  | "%Symbol%"
  | "%Symbol.prototype%"
  | "%SymbolPrototype%"
  | "%SyntaxError%"
  | "%SyntaxErrorPrototype%"
  | "%ThrowTypeError%"
  | "%TypeError%"
  | "%TypeErrorPrototype%"
  | "%TypedArray%"
  | "%TypedArrayPrototype%"
  | "%URIError%"
  | "%URIErrorPrototype%"
  | "%Uint16Array%"
  | "%Uint16ArrayPrototype%"
  | "%Uint32Array%"
  | "%Uint32ArrayPrototype%"
  | "%Uint8Array%"
  | "%Uint8ArrayPrototype%"
  | "%Uint8ClampedArray%"
  | "%Uint8ClampedArrayPrototype%"
  | "%WeakMap%"
  | "%WeakMapPrototype%"
  | "%WeakRef%"
  | "%WeakSet%"
  | "%WeakSetPrototype%"
  | "%decodeURI%"
  | "%decodeURIComponent%"
  | "%encodeURI%"
  | "%encodeURIComponent%"
  | "%eval%"
  | "%isFinite%"
  | "%isNaN%"
  | "%parseFloat%"
  | "%parseInt%"
  | "AggregateError"
  | "Array"
  | "Array.prototype"
  | "Array.prototype.concat"
  | "Array.prototype.entries"
  | "Array.prototype.every"
  | "Array.prototype.filter"
  | "Array.prototype.find"
  | "Array.prototype.findIndex"
  | "Array.prototype.forEach"
  | "Array.prototype.includes"
  | "Array.prototype.indexOf"
  | "Array.prototype.join"
  | "Array.prototype.keys"
  | "Array.prototype.lastIndexOf"
  | "Array.prototype.map"
  | "Array.prototype.pop"
  | "Array.prototype.push"
  | "Array.prototype.reduce"
  | "Array.prototype.reduceRight"
  | "Array.prototype.reverse"
  | "Array.prototype.shift"
  | "Array.prototype.slice"
  | "Array.prototype.some"
  | "Array.prototype.sort"
  | "Array.prototype.splice"
  | "Array.prototype.unshift"
  | "Array.prototype.values"
  | "ArrayBuffer"
  | "ArrayBufferPrototype"
  | "ArrayIteratorPrototype"
  | "ArrayProto_entries"
  | "ArrayProto_forEach"
  | "ArrayProto_keys"
  | "ArrayProto_values"
  | "ArrayPrototype"
  | "AsyncFromSyncIteratorPrototype"
  | "AsyncFunction"
  | "AsyncFunctionPrototype"
  | "AsyncGenerator"
  | "AsyncGeneratorFunction"
  | "AsyncGeneratorPrototype"
  | "AsyncIteratorPrototype"
  | "Atomics"
  | "BigInt"
  | "BigInt64Array"
  | "BigUint64Array"
  | "Boolean"
  | "Boolean.prototype"
  | "BooleanPrototype"
  | "DataView"
  | "DataViewPrototype"
  | "Date"
  | "Date.prototype"
  | "DatePrototype"
  | "Error"
  | "Error.prototype"
  | "ErrorPrototype"
  | "EvalError"
  | "EvalErrorPrototype"
  | "FinalizationRegistry"
  | "Float16Array"
  | "Float32Array"
  | "Float32ArrayPrototype"
  | "Float64Array"
  | "Float64ArrayPrototype"
  | "Function"
  | "Function.prototype"
  | "Function.prototype.apply"
  | "Function.prototype.bind"
  | "Function.prototype.call"
  | "FunctionPrototype"
  | "Generator"
  | "GeneratorFunction"
  | "GeneratorPrototype"
  | "Int16Array"
  | "Int16ArrayPrototype"
  | "Int32Array"
  | "Int32ArrayPrototype"
  | "Int8Array"
  | "Int8ArrayPrototype"
  | "IteratorPrototype"
  | "JSON"
  | "JSON.parse"
  | "JSON.stringify"
  | "JSONParse"
  | "JSONStringify"
  | "Map"
  | "Map.prototype"
  | "MapIteratorPrototype"
  | "MapPrototype"
  | "Math"
  | "Math.abs"
  | "Math.acos"
  | "Math.asin"
  | "Math.atan"
  | "Math.atan2"
  | "Math.ceil"
  | "Math.cos"
  | "Math.exp"
  | "Math.floor"
  | "Math.log"
  | "Math.max"
  | "Math.min"
  | "Math.pow"
  | "Math.random"
  | "Math.round"
  | "Math.sign"
  | "Math.sin"
  | "Math.sqrt"
  | "Math.tan"
  | "Math.trunc"
  | "Number"
  | "Number.prototype"
  | "NumberPrototype"
  | "ObjProto_toString"
  | "ObjProto_valueOf"
  | "Object"
  | "Object.assign"
  | "Object.create"
  | "Object.defineProperties"
  | "Object.defineProperty"
  | "Object.entries"
  | "Object.freeze"
  | "Object.getOwnPropertyDescriptor"
  | "Object.getOwnPropertyDescriptors"
  | "Object.getOwnPropertyNames"
  | "Object.getOwnPropertySymbols"
  | "Object.getPrototypeOf"
  | "Object.is"
  | "Object.isExtensible"
  | "Object.isFrozen"
  | "Object.isSealed"
  | "Object.keys"
  | "Object.preventExtensions"
  | "Object.prototype"
  | "Object.prototype.hasOwnProperty"
  | "Object.prototype.isPrototypeOf"
  | "Object.prototype.propertyIsEnumerable"
  | "Object.prototype.toString"
  | "Object.prototype.valueOf"
  | "Object.seal"
  | "Object.setPrototypeOf"
  | "Object.values"
  | "ObjectPrototype"
  | "Promise"
  | "Promise.all"
  | "Promise.allSettled"
  | "Promise.any"
  | "Promise.prototype"
  | "Promise.prototype.catch"
  | "Promise.prototype.finally"
  | "Promise.prototype.then"
  | "Promise.race"
  | "Promise.reject"
  | "Promise.resolve"
  | "PromiseProto_then"
  | "PromisePrototype"
  | "Promise_all"
  | "Promise_reject"
  | "Promise_resolve"
  | "Proxy"
  | "RangeError"
  | "RangeErrorPrototype"
  | "ReferenceError"
  | "ReferenceErrorPrototype"
  | "Reflect"
  | "Reflect.getPrototypeOf"
  | "RegExp"
  | "RegExp.prototype"
  | "RegExpPrototype"
  | "Set"
  | "Set.prototype"
  | "SetIteratorPrototype"
  | "SetPrototype"
  | "SharedArrayBuffer"
  | "SharedArrayBufferPrototype"
  | "String"
  | "String.prototype"
  | "String.prototype.charAt"
  | "String.prototype.charCodeAt"
  | "String.prototype.concat"
  | "String.prototype.endsWith"
  | "String.prototype.includes"
  | "String.prototype.indexOf"
  | "String.prototype.lastIndexOf"
  | "String.prototype.match"
  | "String.prototype.padEnd"
  | "String.prototype.padStart"
  | "String.prototype.repeat"
  | "String.prototype.replace"
  | "String.prototype.search"
  | "String.prototype.slice"
  | "String.prototype.split"
  | "String.prototype.startsWith"
  | "String.prototype.substring"
  | "String.prototype.toLowerCase"
  | "String.prototype.toUpperCase"
  | "String.prototype.trim"
  | "StringIteratorPrototype"
  | "StringPrototype"
  | "Symbol"
  | "Symbol.prototype"
  | "SymbolPrototype"
  | "SyntaxError"
  | "SyntaxErrorPrototype"
  | "ThrowTypeError"
  | "TypeError"
  | "TypeErrorPrototype"
  | "TypedArray"
  | "TypedArrayPrototype"
  | "URIError"
  | "URIErrorPrototype"
  | "Uint16Array"
  | "Uint16ArrayPrototype"
  | "Uint32Array"
  | "Uint32ArrayPrototype"
  | "Uint8Array"
  | "Uint8ArrayPrototype"
  | "Uint8ClampedArray"
  | "Uint8ClampedArrayPrototype"
  | "WeakMap"
  | "WeakMapPrototype"
  | "WeakRef"
  | "WeakSet"
  | "WeakSetPrototype"
  | "decodeURI"
  | "decodeURIComponent"
  | "encodeURI"
  | "encodeURIComponent"
  | "eval"
  | "isFinite"
  | "isNaN"
  | "parseFloat"
  | "parseInt"
  | string // Allow any string for dynamic access

/**
 * Get a cached JavaScript intrinsic value by name.
 *
 * Intrinsics are retrieved from a cache that is populated at module load time,
 * ensuring you get pristine versions of built-in JavaScript objects and functions
 * before they can be modified by other code.
 *
 * @param name - The intrinsic name, with or without % delimiters (e.g., 'Array' or '%Array%')
 * @param allowMissing - If false (default), throws when intrinsic doesn't exist. If true, returns undefined.
 * @returns The cached intrinsic value
 *
 * @throws {TypeError} If `name` is not a non-empty string
 * @throws {TypeError} If `allowMissing` is provided but is not a boolean
 * @throws {SyntaxError} If `name` has invalid syntax (e.g., mismatched % delimiters)
 * @throws {TypeError} If the intrinsic exists but is not available in the current environment and `allowMissing` is false
 * @throws {SyntaxError} If the intrinsic name does not exist
 *
 * @example
 * // Get Array.prototype.push
 * const $push = GetIntrinsic('%Array.prototype.push%');
 * const arr = [1, 2, 3];
 * $push.call(arr, 4); // arr is now [1, 2, 3, 4]
 *
 * @example
 * // Get Object.create
 * const $create = GetIntrinsic('%Object.create%');
 * const obj = $create(null); // Object with no prototype
 *
 * @example
 * // Safe handling of potentially missing intrinsics
 * const $asyncGen = GetIntrinsic('%AsyncGeneratorFunction%', true);
 * if ($asyncGen) {
 *   // Use async generator functionality
 * }
 *
 * @example
 * // Protect against prototype pollution
 * Array.prototype.push = function() { console.log('hacked!'); };
 * const $push = GetIntrinsic('%Array.prototype.push%');
 * const arr = [1, 2];
 * $push.call(arr, 3); // Still works correctly, arr is [1, 2, 3]
 */
declare function GetIntrinsic(name: IntrinsicName, allowMissing?: false): any

/**
 * Get a cached JavaScript intrinsic value by name, returning undefined if not available.
 *
 * @param name - The intrinsic name, with or without % delimiters
 * @param allowMissing - Must be true to use this overload
 * @returns The cached intrinsic value, or undefined if not available
 *
 * @example
 * const $asyncGen = GetIntrinsic('%AsyncGeneratorFunction%', true);
 * // $asyncGen may be undefined in older environments
 */
declare function GetIntrinsic(
  name: IntrinsicName,
  allowMissing: true,
): any | undefined

export = GetIntrinsic
